package com.rwin.tag.util.geocoding;

import java.util.HashMap;
import java.util.Map;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.rwin.tag.util.Util;

// NOTE this is autogenerated using:  http://www.jsonschema2pojo.org/
@JsonInclude(JsonInclude.Include.NON_NULL)
@Generated("org.jsonschema2pojo")
@JsonPropertyOrder({ "place_id", "licence", "osm_type", "osm_id", "lat", "lon",
        "display_name", "address" })
public class GeocodeRequest {

    public static GeocodeRequest parse(String geoRequest) {
        return Util.parse(geoRequest, GeocodeRequest.class);
    }

    @JsonProperty("place_id")
    private String place_id;
    @JsonProperty("licence")
    private String licence;
    @JsonProperty("osm_type")
    private String osm_type;
    @JsonProperty("osm_id")
    private String osm_id;
    @JsonProperty("lat")
    private String lat;
    @JsonProperty("lon")
    private String lon;
    @JsonProperty("display_name")
    private String display_name;
    @JsonProperty("address")
    private Address address;
    private Map<String, Object> additionalProperties = new HashMap<String, Object>();

    @JsonProperty("place_id")
    public String getPlace_id() {
        return place_id;
    }

    @JsonProperty("place_id")
    public void setPlace_id(String place_id) {
        this.place_id = place_id;
    }

    @JsonProperty("licence")
    public String getLicence() {
        return licence;
    }

    @JsonProperty("licence")
    public void setLicence(String licence) {
        this.licence = licence;
    }

    @JsonProperty("osm_type")
    public String getOsm_type() {
        return osm_type;
    }

    @JsonProperty("osm_type")
    public void setOsm_type(String osm_type) {
        this.osm_type = osm_type;
    }

    @JsonProperty("osm_id")
    public String getOsm_id() {
        return osm_id;
    }

    @JsonProperty("osm_id")
    public void setOsm_id(String osm_id) {
        this.osm_id = osm_id;
    }

    @JsonProperty("lat")
    public String getLat() {
        return lat;
    }

    @JsonProperty("lat")
    public void setLat(String lat) {
        this.lat = lat;
    }

    @JsonProperty("lon")
    public String getLon() {
        return lon;
    }

    @JsonProperty("lon")
    public void setLon(String lon) {
        this.lon = lon;
    }

    @JsonProperty("display_name")
    public String getDisplay_name() {
        return display_name;
    }

    @JsonProperty("display_name")
    public void setDisplay_name(String display_name) {
        this.display_name = display_name;
    }

    @JsonProperty("address")
    public Address getAddress() {
        return address;
    }

    @JsonProperty("address")
    public void setAddress(Address address) {
        this.address = address;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

}